name: Build Promtail releases
on:
  # Manual trigger
  workflow_call:
    inputs:
      release:
        required: true
        type: string

jobs:
  build:
    name: Build Promtail statically
    runs-on: ubuntu-latest
    steps:
      - name: Trigger release build
        # If we do not have the tag we expect, trigger the new build
        #if: ${{ steps.loki-latest-release.outputs.release != '' }}
        run: "echo ${{inputs.release}}"
