name: Build and release static Promtail

on:
  workflow_call:
    inputs:
      upstream_promtail_release:
        required: true
        type: string

jobs:
  build:
    name: Detect new releases
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "We have to build ${{inputs.upstream_promtail_release}}"
