name: Check for new Promtail releases
on:
  # Manual trigger
  workflow_dispatch:
  # Check regularly the upstream every four hours
  schedule:
    - cron:  '0 0,4,8,12,16,20 * * *'

jobs:
  check:
    name: Detect new releases
    runs-on: ubuntu-latest
    outputs:
      release: ${{steps.check.outputs.release}}
    steps:
      # Find out what is the latest release of grafana/loki
      - id: loki-latest-release
        uses: pozetroninc/github-action-get-latest-release@v0.5.0
        with:
          repository: grafana/loki
          excludes: prerelease, draft
      # Check out the tags of our repo to compare
      - name: Checkout canonical/loki-k8s-operator
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: check
        name: Check for new releases
        run: |
          release=$(git show-ref --tags promtail-${{steps.loki-latest-release.outputs.release}} --quiet }} && echo -n '' || echo '${{ steps.loki-latest-release.outputs.release }}' )
          echo "::set-output name=release::${release}"

  create-tag:
    name: Create shallow tag
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.release
    steps:
      # Checkout the tag with a shallow clone (no parent commits)
      - name: Checkout grafana/loki
        uses: actions/checkout@v2
        with:
          repository: grafana/loki
          ref: ${{needs.check.outputs.release}}
          fetch-depth: 1
      # Create a new tag based on the shallow clone, and push it
      # to canonical/loki-k8s-operator
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: promtail-${{needs.check.outputs.release}}
          message: "Release ${{needs.check.outputs.release}} of the grafana/loki repository"


  # trigger-build:
  #   uses: ./.github/workflows/build-promtail-release.yaml
  #   needs: create-tag
  #   if: ${{ needs.release-check.outputs.release != '' }}
  #   with:
  #     release: ${{needs.release-check.outputs.release}}
